In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
ad_data=pd.read_csv('advertising.csv')

In [24]:
ad_data

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0
...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,Fundamental modular algorithm,Duffystad,1,Lebanon,2016-02-11 21:49:00,1
996,51.30,45,67782.17,134.42,Grass-roots cohesive monitoring,New Darlene,1,Bosnia and Herzegovina,2016-04-22 02:07:01,1
997,51.63,51,42415.72,120.37,Expanded intangible solution,South Jessica,1,Mongolia,2016-02-01 17:24:57,1
998,55.55,19,41920.79,187.95,Proactive bandwidth-monitored policy,West Steven,0,Guatemala,2016-03-24 02:35:54,0
999,45.01,26,29875.80,178.35,Virtual 5thgeneration emulation,Ronniemouth,0,Brazil,2016-06-03 21:43:21,1

In [25]:
ad_data.head()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0

In [26]:
ad_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object
 5   City                      1000 non-null   object
 6   Male                      1000 non-null   int64
 7   Country                   1000 non-null   object
 8   Timestamp                 1000 non-null   object
 9   Clicked on Ad             1000 non-null   int64
dtypes: float64(3), int64(3), object(4)
memory usage: 78.3+ KB

In [27]:
ad_data.describe()

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,Clicked on Ad
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,65.000200,36.009000,55000.000080,180.000100,0.481000,0.50000
std,15.853615,8.785562,13414.634022,43.902339,0.499889,0.50025
min,32.600000,19.000000,13996.500000,104.780000,0.000000,0.00000
25%,51.360000,29.000000,47031.802500,138.830000,0.000000,0.00000
50%,68.215000,35.000000,57012.300000,183.130000,0.000000,0.50000
75%,78.547500,42.000000,65470.635000,218.792500,1.000000,1.00000
max,91.430000,61.000000,79484.800000,269.960000,1.000000,1.00000

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
x=ad_data[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','Male']]
y=ad_data['Clicked on Ad']

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [33]:
predictions= logmodel.predict(x_test)

In [34]:
from sklearn.metrics import classification_report,confusion_matrix

In [35]:
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91       162
           1       0.96      0.85      0.90       168

    accuracy                           0.91       330
   macro avg       0.91      0.91      0.91       330
weighted avg       0.91      0.91      0.91       330

[[156   6]
 [ 25 143]]

In [36]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
predict=(model.predict(x_test))

print(predict)
print(classification_report(y_test,predict))
print(confusion_matrix(y_test,predict))

[1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0
 1 1 1 0 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 1 1 1 0
 1 1 0 1 1 0 1 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 1 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 1 1 0
 0 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1
 1 0 1 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1
 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1
 0 0 1 1 1 1 0 0 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0 0 1
 0 1 1 0 0 1 0 1 1 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 0]
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       162
           1       0.94      0.93      0.93       168

    accuracy                           0.93       330
   macro avg       0.93      0.93      0.93       330
weighted avg       0.93      0.93      0.93       330

[[152  10]
 [ 12 156]]

In [37]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)
predict=model.predict(x_test)
print(confusion_matrix(y_test,predict))
print(classification_report(y_test,predict))

[[155   7]
 [  9 159]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       162
           1       0.96      0.95      0.95       168

    accuracy                           0.95       330
   macro avg       0.95      0.95      0.95       330
weighted avg       0.95      0.95      0.95       330

In [38]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=6)
model=RandomForestClassifier()
model.fit(x_train,y_train)
predict=model.predict(x_test)
print(confusion_matrix(y_test,predict))
print(classification_report(y_test,predict))

[[156   6]
 [  8 160]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.96       162
           1       0.96      0.95      0.96       168

    accuracy                           0.96       330
   macro avg       0.96      0.96      0.96       330
weighted avg       0.96      0.96      0.96       330

In [48]:
iris=sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [49]:
x=iris[['sepal_length','sepal_width','petal_length','petal_width']]
y=iris['species']

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [52]:
x_train

    sepal_length  sepal_width  petal_length  petal_width
29           4.7          3.2           1.6          0.2
65           6.7          3.1           4.4          1.4
43           5.0          3.5           1.6          0.6
36           5.5          3.5           1.3          0.2
38           4.4          3.0           1.3          0.2
..           ...          ...           ...          ...
0            5.1          3.5           1.4          0.2
35           5.0          3.2           1.2          0.2
85           6.0          3.4           4.5          1.6
78           6.0          2.9           4.5          1.5
87           6.3          2.3           4.4          1.3

[112 rows x 4 columns]

In [53]:
y_train

29        setosa
65    versicolor
43        setosa
36        setosa
38        setosa
         ...
0         setosa
35        setosa
85    versicolor
78    versicolor
87    versicolor
Name: species, Length: 112, dtype: object

In [54]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
77            6.7          3.0           5.0          1.7
101           5.8          2.7           5.1          1.9
60            5.0          2.0           3.5          1.0
146           6.3          2.5           5.0          1.9
131           7.9          3.8           6.4          2.0
52            6.9          3.1           4.9          1.5
127           6.1          3.0           4.9          1.8
98            5.1          2.5           3.0          1.1
140           6.7          3.1           5.6          2.4
61            5.9          3.0           4.2          1.5
106           4.9          2.5           4.5          1.7
94            5.6          2.7           4.2          1.3
16            5.4          3.9           1.3          0.4
19            5.1          3.8           1.5          0.3
40            5.0          3.5           1.3          0.3
75            6.6          3.0           4.4          1.4
115           6.4          3.2           5.3          2.3
50            7.0          3.2           4.7          1.4
105           7.6          3.0           6.6          2.1
14            5.8          4.0           1.2          0.2
149           5.9          3.0           5.1          1.8
112           6.8          3.0           5.5          2.1
108           6.7          2.5           5.8          1.8
4             5.0          3.6           1.4          0.2
143           6.8          3.2           5.9          2.3
51            6.4          3.2           4.5          1.5
13            4.3          3.0           1.1          0.1
21            5.1          3.7           1.5          0.4
124           6.7          3.3           5.7          2.1
62            6.0          2.2           4.0          1.0
147           6.5          3.0           5.2          2.0
54            6.5          2.8           4.6          1.5
58            6.6          2.9           4.6          1.3
5             5.4          3.9           1.7          0.4
22            4.6          3.6           1.0          0.2
119           6.0          2.2           5.0          1.5
10            5.4          3.7           1.5          0.2
129           7.2          3.0           5.8          1.6

In [55]:
y_test

77     versicolor
101     virginica
60     versicolor
146     virginica
131     virginica
52     versicolor
127     virginica
98     versicolor
140     virginica
61     versicolor
106     virginica
94     versicolor
16         setosa
19         setosa
40         setosa
75     versicolor
115     virginica
50     versicolor
105     virginica
14         setosa
149     virginica
112     virginica
108     virginica
4          setosa
143     virginica
51     versicolor
13         setosa
21         setosa
124     virginica
62     versicolor
147     virginica
54     versicolor
58     versicolor
5          setosa
22         setosa
119     virginica
10         setosa
129     virginica
Name: species, dtype: object

In [56]:
y_test

77     versicolor
101     virginica
60     versicolor
146     virginica
131     virginica
52     versicolor
127     virginica
98     versicolor
140     virginica
61     versicolor
106     virginica
94     versicolor
16         setosa
19         setosa
40         setosa
75     versicolor
115     virginica
50     versicolor
105     virginica
14         setosa
149     virginica
112     virginica
108     virginica
4          setosa
143     virginica
51     versicolor
13         setosa
21         setosa
124     virginica
62     versicolor
147     virginica
54     versicolor
58     versicolor
5          setosa
22         setosa
119     virginica
10         setosa
129     virginica
Name: species, dtype: object

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
model=LogisticRegression()

In [59]:
model.fit(x_train,y_train)

/Users/dhanilshah/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [60]:
predictions=model.predict(x_test)

In [61]:
predictions

array(['virginica', 'virginica', 'versicolor', 'virginica', 'virginica',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'versicolor', 'setosa', 'setosa', 'setosa',
       'versicolor', 'virginica', 'versicolor', 'virginica', 'setosa',
       'virginica', 'virginica', 'virginica', 'setosa', 'virginica',
       'versicolor', 'setosa', 'setosa', 'virginica', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'setosa', 'setosa',
       'versicolor', 'setosa', 'virginica'], dtype=object)

In [62]:
from sklearn.metrics import confusion_matrix,classification_report

In [63]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.85      0.92      0.88        12
   virginica       0.93      0.88      0.90        16

    accuracy                           0.92        38
   macro avg       0.93      0.93      0.93        38
weighted avg       0.92      0.92      0.92        38

In [64]:
print(confusion_matrix(y_test,predictions))

[[10  0  0]
 [ 0 11  1]
 [ 0  2 14]]

In [66]:
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier()
model1.fit(x_train,y_train)
predict=model1.predict(x_test)
predict
print(classification_report(y_test,predict))
print(confusion_matrix(y_test,predict))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.85      0.92      0.88        12
   virginica       0.93      0.88      0.90        16

    accuracy                           0.92        38
   macro avg       0.93      0.93      0.93        38
weighted avg       0.92      0.92      0.92        38

[[10  0  0]
 [ 0 11  1]
 [ 0  2 14]]

In [67]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(x_train,y_train)
prediction=model.predict(x_test)
prediction
print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.85      0.92      0.88        12
   virginica       0.93      0.88      0.90        16

    accuracy                           0.92        38
   macro avg       0.93      0.93      0.93        38
weighted avg       0.92      0.92      0.92        38

[[10  0  0]
 [ 0 11  1]
 [ 0  2 14]]

In [69]:
from sklearn.neighbors import KNeighborsClassifier
model3=KNeighborsClassifier(n_neighbors=10)
model3.fit(x_train,y_train)
predictionss=model3.predict(x_test)
predictionss
print(classification_report(y_test,predictionss))
print(confusion_matrix(y_test,predictionss))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.83      0.83      0.83        12
   virginica       0.88      0.88      0.88        16

    accuracy                           0.89        38
   macro avg       0.90      0.90      0.90        38
weighted avg       0.89      0.89      0.89        38

[[10  0  0]
 [ 0 10  2]
 [ 0  2 14]]